### ISSUE TITLE
bug: changelog `commit.id` link breaks in monorepo

### ISSUE THREAD

**Issue by jrson83** [Geocld/sparkee#13]
### Description

In `utils/changelog.ts` is the template code:

```
([{{ commit.id | truncate(length=7, end="") }}]({{ commit.id }}))
```

Generates the following markdown example link output:

```md
([a9d4050](a9d4050212a18f6b3bd76e2e41fbb9045d268b80))
```

In singlerepo it works and the link automatic leads to the **commit** url:

```
https://github.com/username/repo/commit/a9d4050212a18f6b3bd76e2e41fbb9045d268b80
```

In monorepo it instead leads to the changelogs repos package root:

```
https://github.com/username/repot/blob/main/packages/core/a9d4050212a18f6b3bd76e2e41fbb9045d268b80
```

### Solution

- Update monorepo template to include the generated url to a users repo, like in JS (I don't know the template syntax):

```js
`https://github.com/${commit.repo.username}/${commit.repo.name}/commit/${commit.id}`
```

@Geocld Can you fix it?

**Comment by Geocld** [comment]
@jrson83 Thks, I get it. I will try to fix this issue in few days.
