### ISSUE TITLE
feat: better `CHANGELOG.md` handling

### ISSUE THREAD

**Issue by jrson83** [Geocld/sparkee#3]
### Summary of the feature being proposed

Add two capabilities:
- If no changelog file exists, add the h1 heading `# Changelog` to the top of `CHANGELOG.md` (following two line breaks)
- Change default behaviour from changelog release `append` to `prepend` (or add an option to use `prepend` or `append`)
  - If `prepend` is enabled and the file `CHANGELOG.md` exists, check if the first line is `# Changelog\n\n` and prepend the new release between heading and last release

### What value does this feature bring?

The `CHANGELOG.md` should have the heading `Changelog` as this is expected.

When using a changelog generator, the expected behaviour is, the new release gets prepended to the top of `CHANGELOG.md`, instead of beeing  appended to the bottom.

EDIT: The heading could also be an userOption `header`, like stated in [conventional-changelog-config-spec](https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.2.0/README.md#header-string).

### Are you willing to implement this feature yourself?

Yes, just let me known!

**Comment by Geocld** [comment]
@jrson83 Thank you for your attention. As you can see, sparkee use [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog)  internal to generate CHANGELOG.md, but as my usage experience, conventional-changelog is hard to use because API and document, now I have plan to implement a new tools for changelog, the purpose is to have better performance and a more flexible API.

**Comment by jrson83** [comment]
@Geocld did you already start working on this? I really would like to use sparkee for a monorepo in production, but this issue is holding me back. If you didn't start yet I could create a temporary PR?

**Comment by Geocld** [comment]
@jrson83 Still working on it，but not finish yet， really look forward to seeing your input. Thanks for your contribution.

**Comment by jrson83** [comment]
@Geocld I didn't work much with streams before, but I got it working after some hours. I gonna do the PR after some optimization and a cleanup tomorrow.

**Comment by jrson83** [comment]
Is it okay for you when I first introduce a PR to improve `typings`? I really like this project and would like to contribute in order to optimize and reduce usage of third party deps size to make it even better!

**Comment by Geocld** [comment]
@jrson83  No problem! you can contribute and optimize what you can do,let us make this project better! thank you!

**Comment by jrson83** [comment]
@Geocld Sorry, I was busy this week. I will complete the PR soon.
Did you work with [rome](https://rome.tools/) before? It has very lightweight dependencies (24MiB) and is much faster then prettier and eslint. We could migrate from them to rome.

**Comment by Geocld** [comment]
@jrson83 I've heard of `rome` but haven't used it yet，this is a good idea to use rome to improve quality of sparkee code, I will try it in next version!

**Comment by jrson83** [comment]
@Geocld awesome. I have setup rome for sparkee already. I will create another PR, you can check if all is good before merging :ok_hand:

**Comment by Geocld** [comment]
@jrson83 I had use [git-cliff](https://github.com/orhun/git-cliff) to generate CHANGELOG, please see this [commit](https://github.com/Geocld/sparkee/commit/581ad1b839cab095d3cb257155e094bd5bb231ca), I will publish this feature in 1.2.0 version after fix some bug!

**Comment by Geocld** [comment]
@jrson83 release on [1.2.0](https://github.com/Geocld/sparkee/tree/1.2.0).

**Comment by jrson83** [comment]
Cool, I will check it out today.

**Comment by jrson83** [comment]
@Geocld Thank you :grin: The new CHANGELOG is awesome! Keep up the good work. I will close this issue.

I want to make some more improvements and will open a new issue for a new improvement you can comment on.
